name: Terraform Destroy Pipeline

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  TF_VAR_db_password: ${{ secrets.TF_DB_PASSWORD }}
  TF_VAR_app_key: ${{ secrets.TF_APP_KEY }}
  TF_VAR_ecr_force_delete: "true"

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init
        working-directory: infra

      - name: Terraform destroy
        run: terraform destroy -auto-approve -lock-timeout=15m
        working-directory: infra
